var abbey10ad;
var abbey10bc;
var abbey11ad;
var abbey12ad;
var abbey13ad;
var abbey13bc;
var abbey14ad;
var abbey15ad;
var abbey16ad;
var abbey1ad;
var abbey2ad;
var abbey2bc;
var abbey31bc;
var abbey33bc;
var abbey37bc;
var abbey3ad;
var abbey4ad;
var abbey5ad;
var abbey5bc;
var abbey6ad;
var abbey6bc;
var abbey7ad;
var abbey8ad;
var abbey8bc;
var abbey9ad;
var academy10ad;
var academy10bc;
var academy11ad;
var academy12ad;
var academy13ad;
var academy13bc;
var academy14ad;
var academy15ad;
var academy16ad;
var academy1ad;
var academy2ad;
var academy2bc;
var academy31bc;
var academy33bc;
var academy37bc;
var academy3ad;
var academy4ad;
var academy5ad;
var academy5bc;
var academy6ad;
var academy6bc;
var academy7ad;
var academy8ad;
var academy8bc;
var academy9ad;
var amphitheatre10ad;
var amphitheatre10bc;
var amphitheatre11ad;
var amphitheatre12ad;
var amphitheatre13ad;
var amphitheatre13bc;
var amphitheatre14ad;
var amphitheatre15ad;
var amphitheatre16ad;
var amphitheatre1ad;
var amphitheatre2ad;
var amphitheatre2bc;
var amphitheatre31bc;
var amphitheatre33bc;
var amphitheatre37bc;
var amphitheatre3ad;
var amphitheatre4ad;
var amphitheatre5ad;
var amphitheatre5bc;
var amphitheatre6ad;
var amphitheatre6bc;
var amphitheatre7ad;
var amphitheatre8ad;
var amphitheatre8bc;
var amphitheatre9ad;
var bridge10ad;
var bridge10bc;
var bridge11ad;
var bridge12ad;
var bridge13ad;
var bridge13bc;
var bridge14ad;
var bridge15ad;
var bridge16ad;
var bridge1ad;
var bridge2ad;
var bridge2bc;
var bridge31bc;
var bridge33bc;
var bridge37bc;
var bridge3ad;
var bridge4ad;
var bridge5ad;
var bridge5bc;
var bridge6ad;
var bridge6bc;
var bridge7ad;
var bridge8ad;
var bridge8bc;
var bridge9ad;
var castle10ad;
var castle10bc;
var castle11ad;
var castle12ad;
var castle13ad;
var castle13bc;
var castle14ad;
var castle15ad;
var castle16ad;
var castle1ad;
var castle2ad;
var castle2bc;
var castle31bc;
var castle33bc;
var castle37bc;
var castle3ad;
var castle4ad;
var castle5ad;
var castle5bc;
var castle6ad;
var castle6bc;
var castle7ad;
var castle8ad;
var castle8bc;
var castle9ad;
var church10ad;
var church10bc;
var church11ad;
var church12ad;
var church13ad;
var church13bc;
var church14ad;
var church15ad;
var church16ad;
var church1ad;
var church2ad;
var church2bc;
var church31bc;
var church33bc;
var church37bc;
var church3ad;
var church4ad;
var church5ad;
var church5bc;
var church6ad;
var church6bc;
var church7ad;
var church8ad;
var church8bc;
var church9ad;
var fort10ad;
var fort10bc;
var fort11ad;
var fort12ad;
var fort13ad;
var fort13bc;
var fort14ad;
var fort15ad;
var fort16ad;
var fort1ad;
var fort2ad;
var fort2bc;
var fort31bc;
var fort33bc;
var fort37bc;
var fort3ad;
var fort4ad;
var fort5ad;
var fort5bc;
var fort6ad;
var fort6bc;
var fort7ad;
var fort8ad;
var fort8bc;
var fort9ad;
var gate10ad;
var gate10bc;
var gate11ad;
var gate12ad;
var gate13ad;
var gate13bc;
var gate14ad;
var gate15ad;
var gate16ad;
var gate1ad;
var gate2ad;
var gate2bc;
var gate31bc;
var gate33bc;
var gate37bc;
var gate3ad;
var gate4ad;
var gate5ad;
var gate5bc;
var gate6ad;
var gate6bc;
var gate7ad;
var gate8ad;
var gate8bc;
var gate9ad;
var monastery10ad;
var monastery10bc;
var monastery11ad;
var monastery12ad;
var monastery13ad;
var monastery13bc;
var monastery14ad;
var monastery15ad;
var monastery16ad;
var monastery1ad;
var monastery2ad;
var monastery2bc;
var monastery31bc;
var monastery33bc;
var monastery37bc;
var monastery3ad;
var monastery4ad;
var monastery5ad;
var monastery5bc;
var monastery6ad;
var monastery6bc;
var monastery7ad;
var monastery8ad;
var monastery8bc;
var monastery9ad;
var mosque10ad;
var mosque10bc;
var mosque11ad;
var mosque12ad;
var mosque13ad;
var mosque13bc;
var mosque14ad;
var mosque15ad;
var mosque16ad;
var mosque1ad;
var mosque2ad;
var mosque2bc;
var mosque31bc;
var mosque33bc;
var mosque37bc;
var mosque3ad;
var mosque4ad;
var mosque5ad;
var mosque5bc;
var mosque6ad;
var mosque6bc;
var mosque7ad;
var mosque8ad;
var mosque8bc;
var mosque9ad;
var palace10ad;
var palace10bc;
var palace11ad;
var palace12ad;
var palace13ad;
var palace13bc;
var palace14ad;
var palace15ad;
var palace16ad;
var palace1ad;
var palace2ad;
var palace2bc;
var palace31bc;
var palace33bc;
var palace37bc;
var palace3ad;
var palace4ad;
var palace5ad;
var palace5bc;
var palace6ad;
var palace6bc;
var palace7ad;
var palace8ad;
var palace8bc;
var palace9ad;
var shrine10ad;
var shrine10bc;
var shrine11ad;
var shrine12ad;
var shrine13ad;
var shrine13bc;
var shrine14ad;
var shrine15ad;
var shrine16ad;
var shrine1ad;
var shrine2ad;
var shrine2bc;
var shrine31bc;
var shrine33bc;
var shrine37bc;
var shrine3ad;
var shrine4ad;
var shrine5ad;
var shrine5bc;
var shrine6ad;
var shrine6bc;
var shrine7ad;
var shrine8ad;
var shrine8bc;
var shrine9ad;
var temple10ad;
var temple10bc;
var temple11ad;
var temple12ad;
var temple13ad;
var temple13bc;
var temple14ad;
var temple15ad;
var temple16ad;
var temple1ad;
var temple2ad;
var temple2bc;
var temple31bc;
var temple33bc;
var temple37bc;
var temple3ad;
var temple4ad;
var temple5ad;
var temple5bc;
var temple6ad;
var temple6bc;
var temple7ad;
var temple8ad;
var temple8bc;
var temple9ad;
var theatre10ad;
var theatre10bc;
var theatre11ad;
var theatre12ad;
var theatre13ad;
var theatre13bc;
var theatre14ad;
var theatre15ad;
var theatre16ad;
var theatre1ad;
var theatre2ad;
var theatre2bc;
var theatre31bc;
var theatre33bc;
var theatre37bc;
var theatre3ad;
var theatre4ad;
var theatre5ad;
var theatre5bc;
var theatre6ad;
var theatre6bc;
var theatre7ad;
var theatre8ad;
var theatre8bc;
var theatre9ad;
var tomb10ad;
var tomb10bc;
var tomb11ad;
var tomb12ad;
var tomb13ad;
var tomb13bc;
var tomb14ad;
var tomb15ad;
var tomb16ad;
var tomb1ad;
var tomb2ad;
var tomb2bc;
var tomb31bc;
var tomb33bc;
var tomb37bc;
var tomb3ad;
var tomb4ad;
var tomb5ad;
var tomb5bc;
var tomb6ad;
var tomb6bc;
var tomb7ad;
var tomb8ad;
var tomb8bc;
var tomb9ad;
var village10ad;
var village10bc;
var village11ad;
var village12ad;
var village13ad;
var village13bc;
var village14ad;
var village15ad;
var village16ad;
var village1ad;
var village2ad;
var village2bc;
var village31bc;
var village33bc;
var village37bc;
var village3ad;
var village4ad;
var village5ad;
var village5bc;
var village6ad;
var village6bc;
var village7ad;
var village8ad;
var village8bc;
var village9ad;

var abbey10ad = L.layerGroup();
var abbey10bc = L.layerGroup();
var abbey11ad = L.layerGroup();
var abbey12ad = L.layerGroup();
var abbey13ad = L.layerGroup();
var abbey13bc = L.layerGroup();
var abbey14ad = L.layerGroup();
var abbey15ad = L.layerGroup();
var abbey16ad = L.layerGroup();
var abbey1ad = L.layerGroup();
var abbey2ad = L.layerGroup();
var abbey2bc = L.layerGroup();
var abbey31bc = L.layerGroup();
var abbey33bc = L.layerGroup();
var abbey37bc = L.layerGroup();
var abbey3ad = L.layerGroup();
var abbey4ad = L.layerGroup();
var abbey5ad = L.layerGroup();
var abbey5bc = L.layerGroup();
var abbey6ad = L.layerGroup();
var abbey6bc = L.layerGroup();
var abbey7ad = L.layerGroup();
var abbey8ad = L.layerGroup();
var abbey8bc = L.layerGroup();
var abbey9ad = L.layerGroup();
var academy10ad = L.layerGroup();
var academy10bc = L.layerGroup();
var academy11ad = L.layerGroup();
var academy12ad = L.layerGroup();
var academy13ad = L.layerGroup();
var academy13bc = L.layerGroup();
var academy14ad = L.layerGroup();
var academy15ad = L.layerGroup();
var academy16ad = L.layerGroup();
var academy1ad = L.layerGroup();
var academy2ad = L.layerGroup();
var academy2bc = L.layerGroup();
var academy31bc = L.layerGroup();
var academy33bc = L.layerGroup();
var academy37bc = L.layerGroup();
var academy3ad = L.layerGroup();
var academy4ad = L.layerGroup();
var academy5ad = L.layerGroup();
var academy5bc = L.layerGroup();
var academy6ad = L.layerGroup();
var academy6bc = L.layerGroup();
var academy7ad = L.layerGroup();
var academy8ad = L.layerGroup();
var academy8bc = L.layerGroup();
var academy9ad = L.layerGroup();
var amphitheatre10ad = L.layerGroup();
var amphitheatre10bc = L.layerGroup();
var amphitheatre11ad = L.layerGroup();
var amphitheatre12ad = L.layerGroup();
var amphitheatre13ad = L.layerGroup();
var amphitheatre13bc = L.layerGroup();
var amphitheatre14ad = L.layerGroup();
var amphitheatre15ad = L.layerGroup();
var amphitheatre16ad = L.layerGroup();
var amphitheatre1ad = L.layerGroup();
var amphitheatre2ad = L.layerGroup();
var amphitheatre2bc = L.layerGroup();
var amphitheatre31bc = L.layerGroup();
var amphitheatre33bc = L.layerGroup();
var amphitheatre37bc = L.layerGroup();
var amphitheatre3ad = L.layerGroup();
var amphitheatre4ad = L.layerGroup();
var amphitheatre5ad = L.layerGroup();
var amphitheatre5bc = L.layerGroup();
var amphitheatre6ad = L.layerGroup();
var amphitheatre6bc = L.layerGroup();
var amphitheatre7ad = L.layerGroup();
var amphitheatre8ad = L.layerGroup();
var amphitheatre8bc = L.layerGroup();
var amphitheatre9ad = L.layerGroup();
var bridge10ad = L.layerGroup();
var bridge10bc = L.layerGroup();
var bridge11ad = L.layerGroup();
var bridge12ad = L.layerGroup();
var bridge13ad = L.layerGroup();
var bridge13bc = L.layerGroup();
var bridge14ad = L.layerGroup();
var bridge15ad = L.layerGroup();
var bridge16ad = L.layerGroup();
var bridge1ad = L.layerGroup();
var bridge2ad = L.layerGroup();
var bridge2bc = L.layerGroup();
var bridge31bc = L.layerGroup();
var bridge33bc = L.layerGroup();
var bridge37bc = L.layerGroup();
var bridge3ad = L.layerGroup();
var bridge4ad = L.layerGroup();
var bridge5ad = L.layerGroup();
var bridge5bc = L.layerGroup();
var bridge6ad = L.layerGroup();
var bridge6bc = L.layerGroup();
var bridge7ad = L.layerGroup();
var bridge8ad = L.layerGroup();
var bridge8bc = L.layerGroup();
var bridge9ad = L.layerGroup();
var castle10ad = L.layerGroup();
var castle10bc = L.layerGroup();
var castle11ad = L.layerGroup();
var castle12ad = L.layerGroup();
var castle13ad = L.layerGroup();
var castle13bc = L.layerGroup();
var castle14ad = L.layerGroup();
var castle15ad = L.layerGroup();
var castle16ad = L.layerGroup();
var castle1ad = L.layerGroup();
var castle2ad = L.layerGroup();
var castle2bc = L.layerGroup();
var castle31bc = L.layerGroup();
var castle33bc = L.layerGroup();
var castle37bc = L.layerGroup();
var castle3ad = L.layerGroup();
var castle4ad = L.layerGroup();
var castle5ad = L.layerGroup();
var castle5bc = L.layerGroup();
var castle6ad = L.layerGroup();
var castle6bc = L.layerGroup();
var castle7ad = L.layerGroup();
var castle8ad = L.layerGroup();
var castle8bc = L.layerGroup();
var castle9ad = L.layerGroup();
var church10ad = L.layerGroup();
var church10bc = L.layerGroup();
var church11ad = L.layerGroup();
var church12ad = L.layerGroup();
var church13ad = L.layerGroup();
var church13bc = L.layerGroup();
var church14ad = L.layerGroup();
var church15ad = L.layerGroup();
var church16ad = L.layerGroup();
var church1ad = L.layerGroup();
var church2ad = L.layerGroup();
var church2bc = L.layerGroup();
var church31bc = L.layerGroup();
var church33bc = L.layerGroup();
var church37bc = L.layerGroup();
var church3ad = L.layerGroup();
var church4ad = L.layerGroup();
var church5ad = L.layerGroup();
var church5bc = L.layerGroup();
var church6ad = L.layerGroup();
var church6bc = L.layerGroup();
var church7ad = L.layerGroup();
var church8ad = L.layerGroup();
var church8bc = L.layerGroup();
var church9ad = L.layerGroup();
var fort10ad = L.layerGroup();
var fort10bc = L.layerGroup();
var fort11ad = L.layerGroup();
var fort12ad = L.layerGroup();
var fort13ad = L.layerGroup();
var fort13bc = L.layerGroup();
var fort14ad = L.layerGroup();
var fort15ad = L.layerGroup();
var fort16ad = L.layerGroup();
var fort1ad = L.layerGroup();
var fort2ad = L.layerGroup();
var fort2bc = L.layerGroup();
var fort31bc = L.layerGroup();
var fort33bc = L.layerGroup();
var fort37bc = L.layerGroup();
var fort3ad = L.layerGroup();
var fort4ad = L.layerGroup();
var fort5ad = L.layerGroup();
var fort5bc = L.layerGroup();
var fort6ad = L.layerGroup();
var fort6bc = L.layerGroup();
var fort7ad = L.layerGroup();
var fort8ad = L.layerGroup();
var fort8bc = L.layerGroup();
var fort9ad = L.layerGroup();
var gate10ad = L.layerGroup();
var gate10bc = L.layerGroup();
var gate11ad = L.layerGroup();
var gate12ad = L.layerGroup();
var gate13ad = L.layerGroup();
var gate13bc = L.layerGroup();
var gate14ad = L.layerGroup();
var gate15ad = L.layerGroup();
var gate16ad = L.layerGroup();
var gate1ad = L.layerGroup();
var gate2ad = L.layerGroup();
var gate2bc = L.layerGroup();
var gate31bc = L.layerGroup();
var gate33bc = L.layerGroup();
var gate37bc = L.layerGroup();
var gate3ad = L.layerGroup();
var gate4ad = L.layerGroup();
var gate5ad = L.layerGroup();
var gate5bc = L.layerGroup();
var gate6ad = L.layerGroup();
var gate6bc = L.layerGroup();
var gate7ad = L.layerGroup();
var gate8ad = L.layerGroup();
var gate8bc = L.layerGroup();
var gate9ad = L.layerGroup();
var monastery10ad = L.layerGroup();
var monastery10bc = L.layerGroup();
var monastery11ad = L.layerGroup();
var monastery12ad = L.layerGroup();
var monastery13ad = L.layerGroup();
var monastery13bc = L.layerGroup();
var monastery14ad = L.layerGroup();
var monastery15ad = L.layerGroup();
var monastery16ad = L.layerGroup();
var monastery1ad = L.layerGroup();
var monastery2ad = L.layerGroup();
var monastery2bc = L.layerGroup();
var monastery31bc = L.layerGroup();
var monastery33bc = L.layerGroup();
var monastery37bc = L.layerGroup();
var monastery3ad = L.layerGroup();
var monastery4ad = L.layerGroup();
var monastery5ad = L.layerGroup();
var monastery5bc = L.layerGroup();
var monastery6ad = L.layerGroup();
var monastery6bc = L.layerGroup();
var monastery7ad = L.layerGroup();
var monastery8ad = L.layerGroup();
var monastery8bc = L.layerGroup();
var monastery9ad = L.layerGroup();
var mosque10ad = L.layerGroup();
var mosque10bc = L.layerGroup();
var mosque11ad = L.layerGroup();
var mosque12ad = L.layerGroup();
var mosque13ad = L.layerGroup();
var mosque13bc = L.layerGroup();
var mosque14ad = L.layerGroup();
var mosque15ad = L.layerGroup();
var mosque16ad = L.layerGroup();
var mosque1ad = L.layerGroup();
var mosque2ad = L.layerGroup();
var mosque2bc = L.layerGroup();
var mosque31bc = L.layerGroup();
var mosque33bc = L.layerGroup();
var mosque37bc = L.layerGroup();
var mosque3ad = L.layerGroup();
var mosque4ad = L.layerGroup();
var mosque5ad = L.layerGroup();
var mosque5bc = L.layerGroup();
var mosque6ad = L.layerGroup();
var mosque6bc = L.layerGroup();
var mosque7ad = L.layerGroup();
var mosque8ad = L.layerGroup();
var mosque8bc = L.layerGroup();
var mosque9ad = L.layerGroup();
var palace10ad = L.layerGroup();
var palace10bc = L.layerGroup();
var palace11ad = L.layerGroup();
var palace12ad = L.layerGroup();
var palace13ad = L.layerGroup();
var palace13bc = L.layerGroup();
var palace14ad = L.layerGroup();
var palace15ad = L.layerGroup();
var palace16ad = L.layerGroup();
var palace1ad = L.layerGroup();
var palace2ad = L.layerGroup();
var palace2bc = L.layerGroup();
var palace31bc = L.layerGroup();
var palace33bc = L.layerGroup();
var palace37bc = L.layerGroup();
var palace3ad = L.layerGroup();
var palace4ad = L.layerGroup();
var palace5ad = L.layerGroup();
var palace5bc = L.layerGroup();
var palace6ad = L.layerGroup();
var palace6bc = L.layerGroup();
var palace7ad = L.layerGroup();
var palace8ad = L.layerGroup();
var palace8bc = L.layerGroup();
var palace9ad = L.layerGroup();
var shrine10ad = L.layerGroup();
var shrine10bc = L.layerGroup();
var shrine11ad = L.layerGroup();
var shrine12ad = L.layerGroup();
var shrine13ad = L.layerGroup();
var shrine13bc = L.layerGroup();
var shrine14ad = L.layerGroup();
var shrine15ad = L.layerGroup();
var shrine16ad = L.layerGroup();
var shrine1ad = L.layerGroup();
var shrine2ad = L.layerGroup();
var shrine2bc = L.layerGroup();
var shrine31bc = L.layerGroup();
var shrine33bc = L.layerGroup();
var shrine37bc = L.layerGroup();
var shrine3ad = L.layerGroup();
var shrine4ad = L.layerGroup();
var shrine5ad = L.layerGroup();
var shrine5bc = L.layerGroup();
var shrine6ad = L.layerGroup();
var shrine6bc = L.layerGroup();
var shrine7ad = L.layerGroup();
var shrine8ad = L.layerGroup();
var shrine8bc = L.layerGroup();
var shrine9ad = L.layerGroup();
var temple10ad = L.layerGroup();
var temple10bc = L.layerGroup();
var temple11ad = L.layerGroup();
var temple12ad = L.layerGroup();
var temple13ad = L.layerGroup();
var temple13bc = L.layerGroup();
var temple14ad = L.layerGroup();
var temple15ad = L.layerGroup();
var temple16ad = L.layerGroup();
var temple1ad = L.layerGroup();
var temple2ad = L.layerGroup();
var temple2bc = L.layerGroup();
var temple31bc = L.layerGroup();
var temple33bc = L.layerGroup();
var temple37bc = L.layerGroup();
var temple3ad = L.layerGroup();
var temple4ad = L.layerGroup();
var temple5ad = L.layerGroup();
var temple5bc = L.layerGroup();
var temple6ad = L.layerGroup();
var temple6bc = L.layerGroup();
var temple7ad = L.layerGroup();
var temple8ad = L.layerGroup();
var temple8bc = L.layerGroup();
var temple9ad = L.layerGroup();
var theatre10ad = L.layerGroup();
var theatre10bc = L.layerGroup();
var theatre11ad = L.layerGroup();
var theatre12ad = L.layerGroup();
var theatre13ad = L.layerGroup();
var theatre13bc = L.layerGroup();
var theatre14ad = L.layerGroup();
var theatre15ad = L.layerGroup();
var theatre16ad = L.layerGroup();
var theatre1ad = L.layerGroup();
var theatre2ad = L.layerGroup();
var theatre2bc = L.layerGroup();
var theatre31bc = L.layerGroup();
var theatre33bc = L.layerGroup();
var theatre37bc = L.layerGroup();
var theatre3ad = L.layerGroup();
var theatre4ad = L.layerGroup();
var theatre5ad = L.layerGroup();
var theatre5bc = L.layerGroup();
var theatre6ad = L.layerGroup();
var theatre6bc = L.layerGroup();
var theatre7ad = L.layerGroup();
var theatre8ad = L.layerGroup();
var theatre8bc = L.layerGroup();
var theatre9ad = L.layerGroup();
var tomb10ad = L.layerGroup();
var tomb10bc = L.layerGroup();
var tomb11ad = L.layerGroup();
var tomb12ad = L.layerGroup();
var tomb13ad = L.layerGroup();
var tomb13bc = L.layerGroup();
var tomb14ad = L.layerGroup();
var tomb15ad = L.layerGroup();
var tomb16ad = L.layerGroup();
var tomb1ad = L.layerGroup();
var tomb2ad = L.layerGroup();
var tomb2bc = L.layerGroup();
var tomb31bc = L.layerGroup();
var tomb33bc = L.layerGroup();
var tomb37bc = L.layerGroup();
var tomb3ad = L.layerGroup();
var tomb4ad = L.layerGroup();
var tomb5ad = L.layerGroup();
var tomb5bc = L.layerGroup();
var tomb6ad = L.layerGroup();
var tomb6bc = L.layerGroup();
var tomb7ad = L.layerGroup();
var tomb8ad = L.layerGroup();
var tomb8bc = L.layerGroup();
var tomb9ad = L.layerGroup();
var village10ad = L.layerGroup();
var village10bc = L.layerGroup();
var village11ad = L.layerGroup();
var village12ad = L.layerGroup();
var village13ad = L.layerGroup();
var village13bc = L.layerGroup();
var village14ad = L.layerGroup();
var village15ad = L.layerGroup();
var village16ad = L.layerGroup();
var village1ad = L.layerGroup();
var village2ad = L.layerGroup();
var village2bc = L.layerGroup();
var village31bc = L.layerGroup();
var village33bc = L.layerGroup();
var village37bc = L.layerGroup();
var village3ad = L.layerGroup();
var village4ad = L.layerGroup();
var village5ad = L.layerGroup();
var village5bc = L.layerGroup();
var village6ad = L.layerGroup();
var village6bc = L.layerGroup();
var village7ad = L.layerGroup();
var village8ad = L.layerGroup();
var village8bc = L.layerGroup();
var village9ad = L.layerGroup();
